#!/bin/bash
#SBATCH --job-name=hpc-test3
#SBATCH --ntasks=1             
#SBATCH --mem=24gb                    
#SBATCH --time=06:00:00   
#SBATCH --partition=standard
#SBATCH --account=bsharp  
#SBATCH --gres=gpu:1 
#SBATCH -o %x.out
# SLURM Inherits your environment. cd $SLURM_SUBMIT_DIR not needed
#pwd; hostname; date


 
module load cuda11/11.0
module load anaconda
source ~/.bashrc

conda activate discobert 

python train.py

