#!/bin/bash
#BATCH --job-name=Sample_Slurm_Job
#SBATCH --ntasks=1             
#SBATCH --mem=24gb                    
#SBATCH --time=06:00:00   
#SBATCH --partition=standard
#SBATCH --account=bsharp  
#SBATCH --gres=gpu:1 

# SLURM Inherits your environment. cd $SLURM_SUBMIT_DIR not needed
#pwd; hostname; date


 
module load cuda11/11.0
module load anaconda
source ~/.bashrc

conda activate discobert 

python /home/u3/alexeeva/discourse/discobert/train.py
